config/routes.rb
UserComments::Application.routes.draw do
  resources :users do
    resources :comments
  end

  root 'users#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user

  validates :body,presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments

  validates :name, presence: true
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :find_user

  def create
    @comment = @user.comments.new(comment_params)
    if @comment.save
      redirect_to user_path(@user)
    else
      redirect_to user_path(@user)
    end
  end

  protected
  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < InheritedResources::Base
  protected
  def permitted_params
    params.permit(user: [:name])
  end

  def collection
    @users ||= end_of_association_chain.order('name asc').page(params[:page]).per(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Twitter Bootstrap 2.3
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Twitter Bootstrap 2.3
.navbar
  .navbar-inner
    .container
      %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .nav-collapse.collapse
        .navbar.navbar-fixed-top
          %nav.navbar-inner
            %ul.nav
              = link_to 'Home', root_path, class: 'brand'
              = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li>
  <%= link_to User.model_name.human.pluralize, users_path %>
</li>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'User Comments'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'User Comments'}"}
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    -# application layout styled for Twitter Bootstrap 2.3
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.error_notification

  = f.input :name

  .form-actions
    = f.submit t('.save',default:'Save'), class: 'btn btn-primary'
    = link_to t('.cancel',default:'Cancel'), :back, class: 'btn'

app/views/users/edit.html.haml
%h1 Users#edit

= render 'form'

app/views/users/index.html.haml
.well
  .pull-right
    %a.btn.btn-large.btn-primary(href=new_user_path)
      %i.icon-plus-sign.icon-white
      = t('.new')

  %h1= User.model_name.human.pluralize

%table.table.table-striped.table-bordered
  %thead
    %th= User.human_attribute_name(:name)
    %th= User.human_attribute_name(:created_at)

  %tbody
    - for user in @users
      %tr
        %td= link_to user.name, user_path(user)
        %td= l(user.created_at,format: :short)

= paginate @users

app/views/users/new.html.haml
%h1 Users#new

= render 'form'

app/views/users/show.html.haml
.well
  .pull-right
    %a.btn.btn-large(href="#{edit_user_path(@user)}")
      %i.icon-edit
      = t('.edit')

  %h1 User#show

%dl
  %dt= User.human_attribute_name :name
  %dd= @user.name

  %dt= User.human_attribute_name :created_at
  %dd= l(@user.created_at,format: :short)

%hr/

%h2
  User's comments

%table.table.table-bordered.table-striped
  %thead
    %th Comments

  %tbody
    - for comment in @user.comments.order('created_at desc')
      %tr
        %td
          = simple_format(comment.body)
          %br/
          %small
            = l(comment.created_at, format: :short)


%h2 New Comment
= simple_form_for(Comment.new,url:user_comments_path(@user)) do |f|
  = f.error_notification

  = f.input :body, as: :text, input_html: { class: 'input-xxlarge', rows: 8 }

  .form-actions
    = f.submit t('.save',default:'Save'), class: 'btn btn-primary'
    = link_to t('.cancel',default:'Cancel'), :back, class: 'btn'